# mcp-tap-auto-source = requesty
base_model = "bytedance-seed/seed-2.0-mini"
reasoning = true
reasoning_options = []

[cost]
input = 0.09999999999999999
output = 0.39999999999999997
cache_read = 0.02
