# mcp-tap-auto-source = requesty
base_model = "google/gemini-2.5-pro"
reasoning = true
reasoning_options = []

[cost]
input = 1.125
output = 9.0
cache_read = 0.27899999999999997
cache_write = 2.1374999999999997

[[cost.tiers]]
tier = { type = "context", size = 200000 }
input = 2.25
output = 13.5
