#!/usr/bin/env python3
"""Sync Requesty model prices into Models.dev provider TOMLs.

Only Requesty routes with a deterministic local ``base_model`` mapping (or
validated AI-assisted fallback mapping) are written. Requesty prices are
converted from USD per token to USD per million tokens, which is the unit used
by the catalog. Files generated by this script are marked with a leading
comment and stale marked files are removed on the next successful run.
"""

from __future__ import annotations

import argparse
import json
import os
import pathlib
import re
import sys
import urllib.error
import urllib.request
from typing import Any

DEFAULT_API_URL = "https://router.requesty.ai/v1/models"
TOKENS_PER_MILLION = 1_000_000
PRICE_DECIMALS = 1_000_000
AUTO_SOURCE_MARKER = "# mcp-tap-auto-source = requesty"
OPENROUTER_API_URL = "https://openrouter.ai/api/v1/chat/completions"
DEFAULT_AI_MODEL = "meta-llama/llama-3.3-70b-instruct"
CACHE_FILE_NAME = ".requesty_ai_mapping_cache.json"

ANTHROPIC_DOT_ZERO = re.compile(r"^claude-(?:opus|sonnet|haiku)-(\d+)$")
MODEL_LAB_ALIASES = {
    "bytedance": "bytedance-seed",
    "minimax": "minimaxi",
    "moonshot": "moonshotai",
    "zai": "zhipuai",
    "z-ai": "zhipuai",
    "zai-org": "zhipuai",
}


def parse_args() -> argparse.Namespace:
    repo_root = pathlib.Path(__file__).resolve().parents[2]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--api-url",
        default=os.environ.get("REQUESTY_API_URL", DEFAULT_API_URL),
        help="Requesty model catalog URL",
    )
    parser.add_argument(
        "--output-dir",
        type=pathlib.Path,
        default=repo_root / "providers" / "requesty" / "models",
        help="Target directory for generated Requesty TOMLs",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Resolve and report models without writing files",
    )
    parser.add_argument(
        "--ai-model",
        default=os.environ.get("REQUESTY_AI_MODEL", DEFAULT_AI_MODEL),
        help="OpenRouter model for AI fallback mapping",
    )
    parser.add_argument(
        "--disable-ai",
        action="store_true",
        help="Disable OpenRouter AI mapping fallback",
    )
    parser.add_argument(
        "--enable-heuristics",
        action="store_true",
        help="Enable deterministic heuristic rules fallback",
    )
    parser.add_argument(
        "--clear-cache",
        action="store_true",
        help="Clear persistent AI mapping cache before running",
    )
    return parser.parse_args()


def fetch_models(api_url: str) -> list[dict[str, Any]]:
    headers = {"Accept": "application/json"}
    api_key = os.environ.get("REQUESTY_API_KEY", "").strip()
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"

    request = urllib.request.Request(api_url, headers=headers)
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            payload = json.load(response)
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")[:500]
        raise RuntimeError(f"Requesty API returned HTTP {exc.code}: {body}") from exc
    except urllib.error.URLError as exc:
        raise RuntimeError(f"Requesty API request failed: {exc.reason}") from exc
    except json.JSONDecodeError as exc:
        raise RuntimeError("Requesty API returned invalid JSON") from exc

    if not isinstance(payload, dict) or not isinstance(payload.get("data"), list):
        raise RuntimeError("Requesty API response does not contain a data list")
    return [record for record in payload["data"] if isinstance(record, dict)]


def load_canonical_ids(repo_root: pathlib.Path) -> set[str]:
    models_root = repo_root / "models"
    return {
        path.relative_to(models_root).with_suffix("").as_posix()
        for path in models_root.rglob("*.toml")
        if path.is_file()
    }


def resolve_base_model(
    record: dict[str, Any],
    canonical_ids: set[str],
    enable_heuristics: bool = False,
) -> str | None:
    model_lab = record.get("model_lab")
    model_name = record.get("model_canonical_name")
    if not isinstance(model_lab, str) or not isinstance(model_name, str):
        return None

    lab_lower = model_lab.lower()
    labs = [lab_lower]
    mapped_lab = MODEL_LAB_ALIASES.get(lab_lower)
    if mapped_lab is not None:
        labs.insert(0, mapped_lab)

    # 1. Exact match with lab candidates
    for lab in dict.fromkeys(labs):
        candidate = f"{lab}/{model_name}"
        if candidate in canonical_ids:
            return candidate

    if not enable_heuristics:
        return None

    # 2. Normalized separators (spaces, underscores to hyphens)
    norm_name = re.sub(r"[\s_]+", "-", model_name).lower()
    for lab in dict.fromkeys(labs):
        candidate = f"{lab}/{norm_name}"
        if candidate in canonical_ids:
            return candidate

    # 3. Anthropic major version alias (e.g. claude-sonnet-4 -> claude-sonnet-4-0)
    if lab_lower == "anthropic":
        match = ANTHROPIC_DOT_ZERO.match(norm_name)
        if match:
            candidate = f"anthropic/{norm_name}-0"
            if candidate in canonical_ids:
                return candidate

    # 4. OpenAI chat suffix alias (e.g. gpt-5.1-chat -> gpt-5.1-chat-latest)
    if lab_lower == "openai" and norm_name.endswith("-chat"):
        candidate = f"openai/{norm_name}-latest"
        if candidate in canonical_ids:
            return candidate

    # 5. Meta prefix / suffix normalization
    if lab_lower == "meta":
        clean_name = norm_name
        if clean_name.startswith("meta-"):
            clean_name = clean_name[5:]
        if clean_name.endswith("-turbo"):
            clean_name = clean_name[:-6]
        candidate = f"meta/{clean_name}"
        if candidate in canonical_ids:
            return candidate

    # 6. xAI fast variants mapping (e.g. grok-4-fast -> grok-4.1-fast)
    if lab_lower == "xai":
        if norm_name in [
            "grok-4-fast",
            "grok-4-1-fast-reasoning",
            "grok-4-1-fast-non-reasoning",
        ]:
            if "xai/grok-4.1-fast" in canonical_ids:
                return "xai/grok-4.1-fast"

    # 7. NVIDIA normalization and aliases
    if lab_lower == "nvidia" or "nemotron" in norm_name:
        clean_nv = norm_name
        if clean_nv.startswith("nvidia-"):
            clean_nv = clean_nv[7:]
        if f"nvidia/{clean_nv}" in canonical_ids:
            return f"nvidia/{clean_nv}"
        # Strip size suffixes (-30b-a3b, -nvfp4, etc.)
        stripped = re.sub(r"-\d+b(?:-a\d+b)?(?:-instruct|-chat)?$", "", clean_nv, flags=re.I)
        stripped = re.sub(r"-nvfp\d+$", "", stripped, flags=re.I)
        if f"nvidia/{stripped}" in canonical_ids:
            return f"nvidia/{stripped}"
        if "nemotron-lightning-3.5" in stripped:
            swapped = stripped.replace("nemotron-lightning-3.5", "nemotron-3.5-lightning")
            if f"nvidia/{swapped}" in canonical_ids:
                return f"nvidia/{swapped}"
        if stripped == "nemotron-3-ultra" and "nvidia/nemotron-3-ultra-550b-a55b" in canonical_ids:
            return "nvidia/nemotron-3-ultra-550b-a55b"
        if stripped == "nemotron-3-nano-omni" and "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning" in canonical_ids:
            return "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning"

    # 8. Single unique basename match (original or normalized)
    for target_name in dict.fromkeys([model_name.lower(), norm_name]):
        basename_matches = [
            model_id for model_id in canonical_ids if model_id.rsplit("/", 1)[-1].lower() == target_name
        ]
        if len(basename_matches) == 1:
            return basename_matches[0]

    return None


def price_per_million(value: Any) -> float | None:
    if not isinstance(value, (int, float)) or isinstance(value, bool):
        return None
    return round(value * TOKENS_PER_MILLION, PRICE_DECIMALS)


def load_ai_cache(repo_root: pathlib.Path) -> dict[str, str | None]:
    cache_path = repo_root / CACHE_FILE_NAME
    if not cache_path.is_file():
        return {}
    try:
        data = json.loads(cache_path.read_text(encoding="utf-8"))
        if isinstance(data, dict):
            return {str(k): v if isinstance(v, str) or v is None else None for k, v in data.items()}
    except Exception:
        pass
    return {}


def save_ai_cache(repo_root: pathlib.Path, cache: dict[str, str | None]) -> None:
    cache_path = repo_root / CACHE_FILE_NAME
    try:
        cache_path.write_text(
            json.dumps(cache, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
    except Exception as exc:
        print(f"Warning: Failed to save AI mapping cache: {exc}", file=sys.stderr)


def query_openrouter_for_mappings(
    unresolved_records: list[dict[str, Any]],
    canonical_ids: set[str],
    model_name: str,
    api_key: str,
) -> dict[str, str | None]:
    if not unresolved_records:
        return {}

    # Filter out empty/policy entries
    valid_records = [
        r
        for r in unresolved_records
        if r.get("model_lab") and r.get("model_canonical_name") and not str(r.get("id", "")).startswith("policy/")
    ]
    if not valid_records:
        return {}

    # Extract distinct items to map
    items_to_query: list[dict[str, Any]] = []
    seen_keys: set[tuple[str, str]] = set()
    for r in valid_records:
        lab = str(r.get("model_lab") or "").strip()
        name = str(r.get("model_canonical_name") or "").strip()
        pair = (lab, name)
        if pair not in seen_keys:
            seen_keys.add(pair)
            items_to_query.append(
                {
                    "model_lab": lab,
                    "model_canonical_name": name,
                    "display_name": r.get("name") or r.get("display_name"),
                }
            )

    system_prompt = (
        "You are an expert AI model catalog mapper for models.dev.\n"
        "Your goal is to match external provider model names to the most accurate canonical model ID from ALLOWED_CANONICAL_IDS.\n\n"
        "Matching & Equivalence Rules:\n"
        "1. Major version zero: Anthropic models without minor dot version (e.g. 'claude-sonnet-4', 'claude-opus-4') map to '-4-0' (e.g. 'anthropic/claude-sonnet-4-0', 'anthropic/claude-opus-4-0').\n"
        "2. Chat alias: OpenAI '-chat' models without date/version (e.g. 'gpt-5.1-chat', 'gpt-5.2-chat', 'gpt-5.3-chat') map to their '-latest' counterpart (e.g. 'openai/gpt-5.1-chat-latest', 'openai/gpt-5.2-chat-latest', 'openai/gpt-5.3-chat-latest').\n"
        "3. Provider/Inference wrappers & prefixes: Ignore provider prefixes/suffixes like 'meta-', '-turbo', '-fp8', '-nvfp4', '-instruct' if the underlying base model is clear (e.g. 'meta/meta-llama-3.1-8b-instruct-turbo' -> 'meta/llama-3.1-8b-instruct', 'meta/llama-3.3-70b-instruct-turbo' -> 'meta/llama-3.3-70b-instruct').\n"
        "4. NVIDIA Nemotron variants: Map parameter/MoE variants (e.g. 'nemotron-3.5-lightning-30b-a3b' -> 'nvidia/nemotron-3.5-lightning', 'nvidia-nemotron-3-ultra' -> 'nvidia/nemotron-3-ultra-550b-a55b', 'nemotron-3-nano-omni' -> 'nvidia/nemotron-3-nano-omni-30b-a3b-reasoning', 'nvidia-nemotron-3-super-120b-a12b' -> 'nvidia/nemotron-3-super-120b-a12b').\n"
        "5. xAI fast variants: 'grok-4-fast', 'grok-4-1-fast-reasoning', 'grok-4-1-fast-non-reasoning' map to 'xai/grok-4.1-fast'.\n"
        "6. Separator normalization: Spaces and underscores in names (e.g. 'Kimi K2.5', 'deepseek_v3') map to hyphenated IDs (e.g. 'moonshotai/kimi-k2.5', 'deepseek/deepseek-v3').\n"
        "7. If a model has NO equivalent in ALLOWED_CANONICAL_IDS (e.g. hermes-4, wizardlm-2, mythomax, kat-coder, ling-2.6, baichuan-m2), return null.\n"
        "8. STRICT VALIDATION: The value MUST be an exact string present in ALLOWED_CANONICAL_IDS or null. Never invent IDs.\n\n"
        "Output Format:\n"
        "Respond ONLY with a valid JSON object mapping each 'model_lab/model_canonical_name' to the matching canonical ID string or null."
    )

    user_prompt = (
        f"ALLOWED_CANONICAL_IDS ({len(canonical_ids)}):\n"
        f"{json.dumps(sorted(canonical_ids), ensure_ascii=False)}\n\n"
        f"ITEMS_TO_MAP ({len(items_to_query)}):\n"
        f"{json.dumps(items_to_query, indent=2, ensure_ascii=False)}\n"
    )

    payload = {
        "model": model_name,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        "response_format": {"type": "json_object"},
        "temperature": 0.0,
    }

    req = urllib.request.Request(
        OPENROUTER_API_URL,
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            "HTTP-Referer": "https://github.com/PCODE-pl/MCPTap-Pareto",
            "X-Title": "MCPTap Requesty Model Sync",
        },
    )

    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            data = json.load(resp)
            content = data["choices"][0]["message"]["content"]
            parsed = json.loads(content)
            if isinstance(parsed, dict):
                # Hard validation: only allow canonical IDs that exist
                validated: dict[str, str | None] = {}
                for k, v in parsed.items():
                    if isinstance(v, str) and v in canonical_ids:
                        validated[k] = v
                    else:
                        validated[k] = None
                return validated
    except Exception as exc:
        print(f"Warning: OpenRouter AI mapping query failed: {exc}", file=sys.stderr)

    return {}


def build_cost(record: dict[str, Any]) -> dict[str, Any] | None:
    input_price = price_per_million(record.get("input_price"))
    output_price = price_per_million(record.get("output_price"))
    if input_price is None or output_price is None:
        return None

    cost: dict[str, Any] = {"input": input_price, "output": output_price}
    for source, target in (
        ("cached_price", "cache_read"),
        ("caching_price", "cache_write"),
    ):
        converted = price_per_million(record.get(source))
        if converted is not None and converted > 0:
            cost[target] = converted

    pricing = record.get("pricing")
    if isinstance(pricing, list):
        tiers = []
        for band in pricing[1:]:
            if not isinstance(band, dict):
                continue
            threshold = band.get("prompt_tokens_threshold")
            tier_input = price_per_million(band.get("input_price", record.get("input_price")))
            tier_output = price_per_million(band.get("output_price", record.get("output_price")))
            if not isinstance(threshold, (int, float)) or tier_input is None or tier_output is None:
                continue
            tiers.append(
                {
                    "threshold": int(threshold),
                    "input": tier_input,
                    "output": tier_output,
                }
            )
        if tiers:
            cost["tiers"] = tiers

    return cost


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def model_path(model_id: str) -> pathlib.PurePosixPath | None:
    parts = model_id.split("/")
    if not parts or any(not part or part in {".", ".."} for part in parts):
        return None
    if any(re.search(r"[\x00-\x1f]", part) for part in parts):
        return None
    return pathlib.PurePosixPath(*parts[:-1], f"{parts[-1]}.toml")


def render_toml(base_model: str, record: dict[str, Any], cost: dict[str, Any]) -> str:
    reasoning = bool(record.get("supports_reasoning", False))
    lines = [
        AUTO_SOURCE_MARKER,
        f"base_model = {toml_string(base_model)}",
        f"reasoning = {str(reasoning).lower()}",
    ]
    if reasoning:
        lines.append("reasoning_options = []")

    lines.extend(["", "[cost]", f"input = {cost['input']}", f"output = {cost['output']}"])
    if "cache_read" in cost:
        lines.append(f"cache_read = {cost['cache_read']}")
    if "cache_write" in cost:
        lines.append(f"cache_write = {cost['cache_write']}")
    for tier in cost.get("tiers", []):
        lines.extend(
            [
                "",
                "[[cost.tiers]]",
                f'tier = {{ type = "context", size = {tier["threshold"]} }}',
                f"input = {tier['input']}",
                f"output = {tier['output']}",
            ]
        )
    return "\n".join(lines) + "\n"


def is_auto_source_file(path: pathlib.Path) -> bool:
    try:
        first_line = path.open(encoding="utf-8").readline().strip()
    except OSError:
        return False
    return first_line == AUTO_SOURCE_MARKER


def prune_auto_source_files(
    output_dir: pathlib.Path,
    current_paths: set[pathlib.PurePosixPath],
    dry_run: bool,
) -> list[str]:
    if not output_dir.is_dir():
        return []

    pruned: list[str] = []
    for path in output_dir.rglob("*.toml"):
        relative_path = pathlib.PurePosixPath(path.relative_to(output_dir).as_posix())
        if relative_path in current_paths or not is_auto_source_file(path):
            continue
        pruned.append(relative_path.as_posix())
        if not dry_run:
            path.unlink()

    if not dry_run:
        for directory in sorted(
            (path for path in output_dir.rglob("*") if path.is_dir()),
            reverse=True,
        ):
            try:
                directory.rmdir()
            except OSError:
                pass

    return pruned


def sync(
    repo_root: pathlib.Path,
    records: list[dict[str, Any]],
    output_dir: pathlib.Path,
    dry_run: bool,
    ai_model: str = DEFAULT_AI_MODEL,
    disable_ai: bool = False,
    enable_heuristics: bool = False,
    clear_cache: bool = False,
) -> dict[str, Any]:
    canonical_ids = load_canonical_ids(repo_root)
    matched: list[str] = []
    skipped_mapping: list[str] = []
    skipped_price: list[str] = []
    skipped_invalid_id: list[str] = []
    written: list[str] = []
    seen_paths: set[pathlib.PurePosixPath] = set()

    # Filter out router policy entries upfront
    records = [
        r
        for r in records
        if not str(r.get("id", "")).startswith("policy/") and (r.get("model_lab") or r.get("model_canonical_name"))
    ]

    # Load persistent AI cache
    if clear_cache and not dry_run:
        save_ai_cache(repo_root, {})
        ai_cache = {}
    else:
        ai_cache = load_ai_cache(repo_root)
    ai_key = os.environ.get("OPENROUTER_API_KEY", "").strip()
    ai_cache_modified = False

    # AI is evaluated FIRST:
    # 1. Check which models are unmapped in AI cache and need an OpenRouter query
    if not disable_ai and ai_key:
        unresolved_for_ai: list[dict[str, Any]] = []
        for record in records:
            lab = str(record.get("model_lab") or "").strip()
            name = str(record.get("model_canonical_name") or "").strip()
            pair_key = f"{lab}/{name}"
            # Check exact match first
            exact_match = resolve_base_model(record, canonical_ids, enable_heuristics=False)
            if exact_match is None and (pair_key not in ai_cache or ai_cache[pair_key] is None):
                unresolved_for_ai.append(record)

        # Query OpenRouter for missing items in cache
        if unresolved_for_ai:
            ai_mappings = query_openrouter_for_mappings(unresolved_for_ai, canonical_ids, ai_model, ai_key)
            for k, v in ai_mappings.items():
                ai_cache[k] = v
                ai_cache_modified = True

    if ai_cache_modified and not dry_run:
        save_ai_cache(repo_root, ai_cache)

    # Resolution order for each record:
    # 1. Exact match (model_lab / model_canonical_name with aliases)
    # 2. AI mapping (if enabled and present in cache)
    # 3. Deterministic heuristics (only if enable_heuristics=True)
    for record in records:
        model_id = record.get("id")
        display_id = model_id if isinstance(model_id, str) else "<missing id>"

        # Step 1: Exact match
        base_model = resolve_base_model(record, canonical_ids, enable_heuristics=False)

        # Step 2: AI mapping (evaluated first before heuristics)
        if base_model is None and not disable_ai:
            lab = str(record.get("model_lab") or "").strip()
            name = str(record.get("model_canonical_name") or "").strip()
            cached_val = ai_cache.get(f"{lab}/{name}")
            if isinstance(cached_val, str) and cached_val in canonical_ids:
                base_model = cached_val

        # Step 3: Heuristics fallback (only if enabled)
        if base_model is None and enable_heuristics:
            base_model = resolve_base_model(record, canonical_ids, enable_heuristics=True)

        if base_model is None:
            skipped_mapping.append(
                f"{display_id} (lab={record.get('model_lab')!r}, canonical={record.get('model_canonical_name')!r})"
            )
            continue

        cost = build_cost(record)
        if cost is None:
            skipped_price.append(display_id)
            continue
        if not isinstance(model_id, str):
            skipped_invalid_id.append(display_id)
            continue
        relative_path = model_path(model_id)
        if relative_path is None or relative_path in seen_paths:
            skipped_invalid_id.append(display_id)
            continue

        seen_paths.add(relative_path)
        matched.append(f"{model_id} -> {base_model} [{relative_path.as_posix()}]")
        written.append(relative_path.as_posix())
        destination = output_dir / pathlib.Path(relative_path)
        if not dry_run:
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(render_toml(base_model, record, cost), encoding="utf-8")

    pruned = prune_auto_source_files(output_dir, seen_paths, dry_run)
    return {
        "records": len(records),
        "matched": matched,
        "written": written,
        "pruned": pruned,
        "skipped_mapping": skipped_mapping,
        "skipped_price": skipped_price,
        "skipped_invalid_id": skipped_invalid_id,
    }


def print_bucket(title: str, items: list[str]) -> None:
    print(f"\n{title} ({len(items)})")
    if not items:
        print("  - none")
        return
    for item in items:
        print(f"  - {item}")


def print_summary(summary: dict[str, Any], dry_run: bool) -> None:
    print("Requesty model sync")
    print("===================")
    print(f"Records from API: {summary['records']}")
    print(f"Matched & mapped: {len(summary['matched'])}")
    print(f"Written: {len(summary['written'])}" if not dry_run else f"Would write: {len(summary['written'])}")
    print_bucket("Pruned" if not dry_run else "Would prune", summary["pruned"])
    print_bucket("Skipped: no base_model mapping", summary["skipped_mapping"])
    print_bucket("Skipped: missing price", summary["skipped_price"])
    print_bucket("Skipped: invalid or duplicate model ID", summary["skipped_invalid_id"])


def main() -> None:
    args = parse_args()
    repo_root = pathlib.Path(__file__).resolve().parents[2]
    summary = sync(
        repo_root,
        fetch_models(args.api_url),
        args.output_dir,
        args.dry_run,
        ai_model=args.ai_model,
        disable_ai=args.disable_ai,
        enable_heuristics=args.enable_heuristics,
        clear_cache=args.clear_cache,
    )
    print_summary(summary, args.dry_run)


if __name__ == "__main__":
    try:
        main()
    except (RuntimeError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
