# mcp-tap-auto-source = requesty
base_model = "deepseek/deepseek-v4-pro-0813"
reasoning = true
reasoning_options = []

[cost]
input = 1.1880000000000002
output = 3.564
cache_read = 0.039599999999999996
