# mcp-tap-auto-source = requesty
base_model = "google/gemini-2.5-flash-lite"
reasoning = true
reasoning_options = []

[cost]
input = 0.049999999999999996
output = 0.19999999999999998
cache_read = 0.01
