# mcp-tap-auto-source = requesty
base_model = "anthropic/claude-haiku-4-5"
reasoning = true
reasoning_options = []

[cost]
input = 0.9900000000000001
output = 4.95
cache_read = 0.099
cache_write = 1.2375
