# mcp-tap-auto-source = requesty
base_model = "google/gemini-3.5-flash"
reasoning = true
reasoning_options = []

[cost]
input = 1.4849999999999999
output = 8.91
cache_read = 0.14850000000000002
cache_write = 1.56717
