# mcp-tap-auto-source = requesty
base_model = "google/gemini-3.1-pro-preview"
reasoning = true
reasoning_options = []

[cost]
input = 1.7999999999999998
output = 10.8
cache_read = 0.18
cache_write = 4.05

[[cost.tiers]]
tier = { type = "context", size = 200000 }
input = 3.5999999999999996
output = 16.2
