# mcp-tap-auto-source = requesty
base_model = "google/gemini-3.1-flash-lite"
reasoning = true
reasoning_options = []

[cost]
input = 0.22499999999999998
output = 1.35
cache_read = 0.0225
cache_write = 0.07499700000000001

[[cost.tiers]]
tier = { type = "context", size = 200000 }
input = 0.44999999999999996
output = 2.025
