# mcp-tap-auto-source = requesty
base_model = "google/gemini-3-flash-preview"
reasoning = true
reasoning_options = []

[cost]
input = 0.22499999999999998
output = 1.35
cache_read = 0.0225
cache_write = 0.44999999999999996
