# mcp-tap-auto-source = requesty
base_model = "alibaba/qwen3-coder-plus"
reasoning = false

[cost]
input = 0.8999999999999999
output = 4.5

[[cost.tiers]]
tier = { type = "context", size = 32678 }
input = 1.6199999999999999
output = 8.1

[[cost.tiers]]
tier = { type = "context", size = 131072 }
input = 2.7
output = 13.5

[[cost.tiers]]
tier = { type = "context", size = 262144 }
input = 5.4
output = 54.0
