# mcp-tap-auto-source = requesty
base_model = "alibaba/qwen3.8-max"
reasoning = true
reasoning_options = []

[cost]
input = 1.7999999999999998
output = 5.4
cache_read = 0.22499999999999998
cache_write = 2.25
