# mcp-tap-auto-source = requesty
base_model = "anthropic/claude-sonnet-4-5"
reasoning = true
reasoning_options = []

[cost]
input = 3.3000000000000003
output = 16.5
cache_read = 0.3
cache_write = 4.125

[[cost.tiers]]
tier = { type = "context", size = 200000 }
input = 6.6000000000000005
output = 24.75
